### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Ana-Green** [Virtual-Universe/Virtual-Universe-Early-Dev#28]
3 errors on build  remote, can not build local either.

Best regards,
Enya

**Comment by Ana-Green** [comment]
I can do what I like but I do not get an error free build, in Visual Studio 2015, 2017 I get an error, If I run the batch file I see red lines in the console (DOS window) related to :   Avatar\BakedTextures\XBakesModule.cs(145,66): error CS1003: Syntax error, ',' expected [C:\projects\virtual-universe-early-dev\Universe\Region\CoreModules\Universe.Region.CoreModules.csproj]
1015
  Avatar\BakedTextures\XBakesModule.cs(168,66): error CS1003: Syntax error, ',' expected [C:\projects\virtual-universe-early-dev\Universe\Region\CoreModules\Universe.Region.CoreModules.csproj]

Regards,
Ana Green

**Comment by emperorstarfinder** [comment]
Good morning,

As has been stated previously via a commit message, we are aware of these 2 errors.  they are false errors as we are able to build internally.  Also, this is one reason why we have appVeyor for Windows which allows us to see these errors within a couple of minutes after a commit is pushed.

We build the architecture against the latest mono on Linux, and against Visual Studio 2019 on Windows.  You need to be sure you have .Net Framework 4.6, through 4.7.2 installed in Windows.  Also, do not try to build on Windows Server architectures.

We will be providing weekly builds for Windows, Linux, and Mac OS via our open source project arm website in a few days.

Best Regards,
Emperor Starfinder
CEO
Founder
Governing Body Chair
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Grid Architecture Development, Maintenance
Second Galaxy Development Team

**Comment by Ana-Green** [comment]
Compile errors/warnings  0 , Stops  here:
2019-10-06 07:35:22,457 ERROR [Virtual Universe Server Utils]: Error loading plugin from OpenSim.Services.SimulationService.dll
System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\DSGrid\9009\OpenSim.Services.SimulationService.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'file:///C:\DSGrid\9009\OpenSim.Services.SimulationService.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Universe.Server.Base.ServerUtils.LoadPlugin[T](String dllName, String className, Object[] args) in C:\Users\K-Zero\Pictures\Virtual-Universe-Early-Dev-master\Universe\Server\Base\ServerUtils.cs:line 284

**Comment by emperorstarfinder** [comment]
Good afternoon,

You are getting that error as this repository at the moment is a few commits behind our internal repository.  This has already been corrected and will be available shortly in addition to weekly builds  Please bear with us as we are in the middle of transitioning into our new operating structure so things will likely get behind over the next few days.

Best regard,

Best Regards,
Emperor Starfinder
CEO
Founder
Governing Body Chair
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Grid Architecture Development, Maintenance
Second Galaxy Development Team
Virtual World Research Inc.

**Comment by emperorstarfinder** [comment]
Good morning,

I have uploaded a weekly build.  It is only the built binaries at the moment, however, it does suffice for what is needed for the moment.  It can be found at http://virtual-planets.org/Downloads/WeeklyBuilds/VU-Weekly-Build-1072019-Win64.zip

NOTE: Do not panic should you see error pages saying things on the website cannot be found.  We are in the middle of designing the full website for the open-source project arm.

Best Regards,
Emperor Starfinder
CEO
Founder
Governing Body Chair
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Grid Architecture Development, Maintenance
Second Galaxy Development Team
Virtual World Research Inc.

**Comment by emperorstarfinder** [comment]
Closing as this issue has been resolved.

Best Regards,
Emperor Starfinder
CEO
Founder
Governing Body Chair
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Grid Architecture Development, Maintenance
Second Galaxy Development Team
Virtual World Research Inc.

**Comment by Ana-Green** [comment]
Really, I still get  compile errors but  it's  ok  
Regards,
Ana Green

**Comment by emperorstarfinder** [comment]
The errors you are getting we only see on AppVeyor.  There are only 2 which really are not errors.  You can use the prebuilt weekly build: http://virtual-planets.org/Downloads/WeeklyBuilds/Vu-Weekly-Build-1072019-Win64.zip

However, we are making some major changes in how the servers work sothe current code will be well out of date shortly as we move things closer to being able to bring a better scripting engine and physics engine in.

Best Regards,
Emperor Starfinder
CEO
Founder
Governing Body Chair
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Grid Architecture Development, Maintenance
Second Galaxy Development Team
Virtual World Research Inc.

**Comment by Ana-Green** [comment]
Well emperorstarfinder,
Whatever I do I can NOT download that zip file  👎 
http://virtual-planets.org/Downloads/WeeklyBuilds/Vu-Weekly-Build-1072019-Win64.zip
But that is cool, I am done with even trying ..  you got  no FTP?  

Ciao,
Ana Green

**Comment by Ana-Green** [comment]
Still doesn't  build  that  includes local 

Regards,
Anna Green

**Comment by emperorstarfinder** [comment]
We are already aware of this.  However, because of the upcoming major commits, this issue is actually moot. as the upcoming commits will build.  Please keep in mind there are things we do know about through our testing or through our automated build tools (ci tools) which will tell us issues like this during their build tests.

Best Regards,
Emperor Starfinder
CEO
Founder
Governing Body Chair
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Grid Architecture Development, Maintenance
Second Galaxy Development Team
Virtual World Research Inc.

**Comment by Ana-Green** [comment]
If you are aware of this, that the code will not build why even put it there wait till you got something that can be compiled.

Best Regards,
Anna Green
Work for Intel and CISCO, from the USA, 27 years, SL/LL BetaGrid Tester, Firestorm Beta Tester. started at 9/12/2018 at NASA. 
Computer Center
AFNORTH/AWACS Brunssum [NL/ZL]

**Comment by emperorstarfinder** [comment]
Let me clarify a few things so you understand our process better so we don't keep having this argument about why we do something in a way you may not like.

1. We maintain two versions of all our repositories, these repositories are our public version repository and our private internal repository.  Only members of the development team have access to our internal repositories.  When you report a bug in our public repositories the commits to fix those issues go to the internal repositories first and must meet certain standards of the development team before they are pushed to the public repositories.  Therefore you should keep in mind that just because the fix has not made it to the public repositories, it is likely that it has arrived in the private internal repositories and will be available soon.  Therefore patience is a virtue and is better to demonstrate because that helps us maintain proper order.

2. We use CI (build tools) in both our private and public repositories, these help us identify build issues quicker.  When a build breaks in the public repositories there is no need to panic, we already know about it and it may just be the commit hasn't been pushed to the public repository to fix it yet.   Likewise, we ask that people be patient before jumping to a conclusion.

3. When reporting an issue to us or commenting on an issue on our issue trackers, please refrain from making comments that are not relevant to the actual issue.  For example, telling us, we are a fork of another project is not relevant to an actual issue someone may be reporting to get our assistance with.  By cooperating with us on this we can ensure that issues do not get out of hand and we can keep things going smoothly.  Remember we know our code and our processes better than those reporting an issue will.  

4. We encourage members of our community who use our architecture to help each other.  All we ask is when you comment on an issue or chat with others in our community channels (via discord, mewe, etc.) keep in mind that how you word things can have unintended effects on other users.  If someone perceives you think you know more then they do or you are talking down to them, you likely get a reaction that you didn't intend more often then not.  

5. This is the public version of our Early Development repository.  This is the first step in the public phase of the development process.  There will always be instability and bugs galore in this repository.  If you are running a production level grid (open to the public), we ask that you not use the codebase in this repository for that.  We prefer that you use the codebase in this repository and the Stable Development Repository on an internal testbed grid.  That way you can safely test and report bugs back to us without it affecting the users on your grid.    

6. Everyone should keep in mind, we have no intention of maintaining full compatibility with OpenSimulator (this is regardless of whether people think we are a fork or not therefore whether we are a fork or not is irrelevant to any issue reported to us).  We have made this decision based on the insecurity in the OpenSimulator codebase and the requirements of our stability and security standards.

7. Per the policies of Virtual World Research Inc., all members of the development team will use their signature when commenting on issues.  This helps us know who is handling issues and helps members of our community understand and know who is responsible for the development of various things we provide.  If you are a grid owner and your grid is running on our architecture, by all means, include that in the signature part when you comment on an issue.  We will be keeping a list of all grids that use our architecture and we will be providing that list on our open source project arm website just as soon as we finish the upgrades to the website code.  Otherwise, we ask that you not include companies you work with that have not authorized you to indicate your work for them in your signature.  Remember in certain cases claiming to work for government agencies or other companies can create legal problems for you if that claim is false.  Therefore we ask that you refrain from putting that in a signature in an issue.  Not that we don't appreciate that information, we do not want to see people wind up with legal problems for no reason.  

Because we indicated previously that the upcoming major commits will render this issue moot, I am locking this issue so we do not keep going round and round on a matter that has been resolved and just not yet made it to our public repositories.

Best Regards,
Emperor Starfinder
CEO
Founder
Governing Body Chair
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Grid Architecture Development, Maintenance
Second Galaxy Development Team
Virtual World Research Inc.
